import Vision
import CoreML
import VisionCamera

@objc(DetectObjectsPlugin)
public class DetectObjectsPlugin: FrameProcessorPlugin {
  private var _model: VNCoreMLModel?

  public override init(proxy: VisionCameraProxyHolder, options: [AnyHashable: Any]?) {
    super.init(proxy: proxy, options: options)
    
    print("EVAI: Initializing DetectObjectsPlugin...")
    
    do {
      let configuration = MLModelConfiguration()
      // Use the class name generated by Xcode. 
      // If the file is 'yolov10n.mlpackage', the class name is usually 'yolov10n'.
      let model = try yolov10n(configuration: configuration).model
      _model = try VNCoreMLModel(for: model)
      print("EVAI: CoreML Model loaded successfully.")
    } catch {
      print("EVAI: Error loading CoreML model: \(error)")
    }
  }

  public override func callback(_ frame: Frame, withArguments arguments: [AnyHashable: Any]?) -> Any? {
    guard let model = _model else {
      print("EVAI: Model not initialized.")
      return nil
    }
    
    guard let imageBuffer = CMSampleBufferGetImageBuffer(frame.buffer) else {
      print("EVAI: Could not get image buffer from frame.")
      return nil
    }

    let request = VNCoreMLRequest(model: model)
    // ScaleFill ensures the image is resized to match the model's input size (e.g. 640x640)
    request.imageCropAndScaleOption = .scaleFill

    let handler = VNImageRequestHandler(cvPixelBuffer: imageBuffer, options: [:])
    do {
      try handler.perform([request])
    } catch {
      print("EVAI: Inference error: \(error)")
      return nil
    }

    guard let results = request.results as? [VNRecognizedObjectObservation] else {
      return nil
    }

    return results.map { observation in
      let bounds = observation.boundingBox
      return [
        "label": observation.labels.first?.identifier ?? "unknown",
        "confidence": observation.confidence,
        "x": bounds.origin.x,
        "y": 1 - bounds.origin.y - bounds.size.height,
        "w": bounds.size.width,
        "h": bounds.size.height
      ]
    }
  }
}
